### ISSUE TITLE
Crashing when unsubscribing and resubscribing

### ISSUE THREAD

**Issue by SteveMacenski** [ros2/rmw_fastrtps#341] opened 2019-12-10 21:42 UTC
## Bug report

**Required Info:**

- Operating System: 
  -  Ubuntu 18.04
- Installation type: 
  -  Shipped with Dashing & master both 
- Version or commit hash:
  - 
- DDS implementation: 
  -  Fast-RTPS 
- Client library (if applicable):
  -   rclcpp

#### Steps to reproduce issue

```

```

#### Expected behavior

Able to unsubscribe and resubscribe to a topic often without crashing.

#### Actual behavior

When unsubscribing and resubscribing to a topic during a runtime reset, we're seeing crashing happen frequently. See ticket https://github.com/ros-planning/navigation2/issues/1363

#### Additional information

Error

```
[PARTICIPANT Error] Type : sensor_msgs::msg::dds_::PointCloud2_ Not Registered
```

With various message types. It works fine on bringup so it subscribes fine. Only happens when we attempt to reset a node that will unsubscribe and resubscribe to a topic. Tested broken with 2+ message types in the ROS2 common interfaces

**Comment by dirk-thomas** [comment] 2019-12-10 22:26
Can you please provide reproducible steps (as minimal as possible, so without navigation would be preferred but isn't a requirement).

**Comment by SteveMacenski** [comment] 2019-12-10 22:47
I'm just the messenger. @crdelsey and @mlherd  report it. But I dont think from our discussions its easy to reproduce at the application layer, but it happens over a short time horizon.

**Comment by crdelsey** [comment] 2019-12-10 23:16
I don't have an easy test case implemented at the moment. However, I believe the core of the failure sequence goes something like this:

1. There is must be no publisher for PointCloud2 messages in the system.
2. Create a subscriber to PointCloud2 and let the system settle.
3. Delete the subscriber object and then immediately create a new one on the same node.

In our case, there are a lot of other subscribers and publishers as well as other traffic. I'm not sure at this point how much of that stuff is important to reproduce the problem.

**Comment by dirk-thomas** [comment] 2019-12-10 23:40
> I'm not sure at this point how much of that stuff is important to reproduce the problem.

I would suggest to try coming up with a trivial example (e.g. modifying the demo `listener` to destroy and recreate) to check if that can reproduce the problem.

**Comment by crdelsey** [comment] 2019-12-11 00:21
Well, the simple test didn't do it. It probably won't be till next year when I have time to dig into this in more detail

**Comment by dirk-thomas** [comment] 2020-01-16 18:17
@crdelsey Friendly ping.

**Comment by crdelsey** [comment] 2020-01-16 18:44
I'll try to reproduce this in a few days. I need to get nav2 back to a working state first.

Since this is unlikely to be easy to reproduce, is there any particular information that you'd want to see as a starting point? Wireshark logs? I could set a breakpoint at the line where the error message occurs and provide a core dump.

**Comment by sainimayankmohan** [comment] 2020-08-07 12:45
Hi , I am also getting this error when i am creating subscription to clock message or sensor data image message. It is random and doesn't occur every time. I am resetting a subscription shared pointer to unsubscribe and than subscribe again.

(gdb) bt
#0  0x0000000000000061 in ?? ()
#1  0x00007ffff4d0d65f in rmw_create_subscription () from /home/msaini1/lib/librmw_fastrtps_cpp.so
#2  0x00007ffff739dd72 in rcl_subscription_init () from /home/msaini1/lib/librcl.so
3  0x00007ffff7ad44f9 in rclcpp::SubscriptionBase::SubscriptionBase(std::shared_ptr<rcl_node_t>, rosidl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t const&, bool) () from /home/msaini1/lib/librclcpp.so
#4  0x00000000004b2970 in rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> >::Subscription(std::shared_ptr<rcl_node_t>, rosidl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t const&, rclcpp::AnySubscriptionCallback<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> >, rclcpp::SubscriptionEventCallbacks const&, std::shared_ptr<rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > >) ()
#5  0x00000000004b232c in void __gnu_cxx::new_allocator<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > >::construct<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> >, std::shared_ptr<rcl_node_t>, rosidl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&, rclcpp::AnySubscriptionCallback<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > const&, rclcpp::SubscriptionEventCallbacks const&, std::shared_ptr<rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&>(rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> >*, std::shared_ptr<rcl_node_t>&&, rosidl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&, rclcpp::AnySubscriptionCallback<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > const&, rclcpp::SubscriptionEventCallbacks const&, std::shared_ptr<rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&) ()
#6  0x00000000004b16ed in void std::allocator_traits<std::allocator<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > >::construct<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> >, std::shared_ptr<rcl_node_t>, rosidl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&, rclcpp::AnySubscriptionCallback<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > const&, rclcpp::SubscriptionEventCallbacks const&, std::shared_ptr<rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&>(std::allocator<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > >&, rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> >*, std::shared_ptr<rcl_node_t>&&, rosidl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&, rclcpp::AnySubscriptionCallback<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > const&, rclcpp::SubscriptionEventCallbacks const&, std::shared_ptr<rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&) ()
#7  0x00000000004b0cb7 in std::_Sp_counted_ptr_inplace<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> >, std::allocator<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > >, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<std::shared_ptr<rcl_node_t>, rosidl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&, rclcpp::AnySubscriptionCallback<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > const&, rclcpp::SubscriptionEventCallbacks const&, std::shared_ptr<rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&>(std::allocator<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > >, std::shared_ptr<rcl_node_t>&&, rosidl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&, rclcpp::AnySubscriptionCallback<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > const&, rclcpp::SubscriptionEventCallbacks const&, std::shared_ptr<rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&) ()
#8  0x00000000004afe6b in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> >, std::allocator<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > >, std::shared_ptr<rcl_node_t>, rosidl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&, rclcpp::AnySubscriptionCallback<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > const&, rclcpp::SubscriptionEventCallbacks const&, std::shared_ptr<rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&>(std::_Sp_make_shared_tag, rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> >*, std::allocator<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&, std::shared_ptr<rcl_node_t>&&, rosidl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&, rclcpp::AnySubscriptionCallback<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > const&, rclcpp::SubscriptionEventCallbacks const&, std::shared_ptr<rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&) ()
#9  0x00000000004aeaf7 in std::__shared_ptr<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> >, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > >, std::shared_ptr<rcl_node_t>, rosidl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&, rclcpp::AnySubscriptionCallback<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > const&, rclcpp::SubscriptionEventCallbacks const&, std::shared_ptr<rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&>(std::_Sp_make_shared_tag, std::allocator<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&, std::shared_ptr<rcl_node_t>&&, rosidl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&, rclcpp::AnySubscriptionCallback<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > const&, rclcpp::SubscriptionEventCallbacks const&, std::shared_ptr<rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&) ()
#10 0x00000000004ad869 in std::shared_ptr<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > >::shared_ptr<std::allocator<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > >, std::shared_ptr<rcl_node_t>, rosidl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&, rclcpp::AnySubscriptionCallback<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > const&, rclcpp::SubscriptionEventCallbacks const&, std::shared_ptr<rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&>(std::_Sp_make_shared_tag, std::allocator<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&, std::shared_ptr<rcl_node_t>&&, rosidl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&, rclcpp::AnySubscriptionCallback<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > const&, rclcpp::SubscriptionEventCallbacks const&, std::shared_ptr<rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&) ()
#11 0x00000000004acc2c in std::shared_ptr<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > std::allocate_shared<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> >, std::allocator<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > >, std::shared_ptr<rcl_node_t>, rosidl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&, rclcpp::AnySubscriptionCallback<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > const&, rclcpp::SubscriptionEventCallbacks const&, std::shared_ptr<rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&>(std::allocator<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&, std::shared_ptr<rcl_node_t>&&, rosi---Type <return> to continue, or q <return> to quit---
dl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&, rclcpp::AnySubscriptionCallback<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > const&, rclcpp::SubscriptionEventCallbacks const&, std::shared_ptr<rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&) ()
#12 0x00000000004abdca in std::shared_ptr<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > std::make_shared<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> >, std::shared_ptr<rcl_node_t>, rosidl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&, rclcpp::AnySubscriptionCallback<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > const&, rclcpp::SubscriptionEventCallbacks const&, std::shared_ptr<rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&>(std::shared_ptr<rcl_node_t>&&, rosidl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&, rclcpp::AnySubscriptionCallback<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > const&, rclcpp::SubscriptionEventCallbacks const&, std::shared_ptr<rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&) ()
#13 0x00000000004aa655 in std::shared_ptr<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> >::make_shared<std::shared_ptr<rcl_node_t>, rosidl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&, rclcpp::AnySubscriptionCallback<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > const&, rclcpp::SubscriptionEventCallbacks const&, std::shared_ptr<rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&>(std::shared_ptr<rcl_node_t>&&, rosidl_message_type_support_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t&, rclcpp::AnySubscriptionCallback<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > const&, rclcpp::SubscriptionEventCallbacks const&, std::shared_ptr<rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > const&) ()
#14 0x00000000004a3216 in rclcpp::SubscriptionFactory rclcpp::create_subscription_factory<rosgraph_msgs::msg::Clock_<std::allocator<void> >, Dc::BagManager::DcRpcPlayer::subscribeClock()::{lambda(std::unique_ptr<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::default_delete<rosgraph_msgs::msg::Clock_<std::allocator<void> > > >)#1}, std::allocator<void>, rosgraph_msgs::msg::Clock_<std::allocator<void> >, rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > >(Dc::BagManager::DcRpcPlayer::subscribeClock()::{lambda(std::unique_ptr<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::default_delete<rosgraph_msgs::msg::Clock_<std::allocator<void> > > >)#1}&&, rclcpp::SubscriptionEventCallbacks const&, rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> >::SharedPtr, std::shared_ptr<rosgraph_msgs::msg::Clock_<std::allocator<void> > >)::{lambda(rclcpp::node_interfaces::NodeBaseInterface*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t const&)#1}::operator()(rclcpp::node_interfaces::NodeBaseInterface, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, rcl_subscription_options_t const) const ()
#15 0x00000000004a3f9b in std::_Function_handler<std::shared_ptr<rclcpp::SubscriptionBase> (rclcpp::node_interfaces::NodeBaseInterface*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t const&), rclcpp::SubscriptionFactory rclcpp::create_subscription_factory<rosgraph_msgs::msg::Clock_<std::allocator<void> >, Dc::BagManager::DcRpcPlayer::subscribeClock()::{lambda(std::unique_ptr<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::default_delete<rosgraph_msgs::msg::Clock_<std::allocator<void> > > >)#1}, std::allocator<void>, rosgraph_msgs::msg::Clock_<std::allocator<void> >, rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > >(Dc::BagManager::DcRpcPlayer::subscribeClock()::{lambda(std::unique_ptr<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::default_delete<rosgraph_msgs::msg::Clock_<std::allocator<void> > > >)#1}&&, rclcpp::SubscriptionEventCallbacks const&, rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> >::SharedPtr, std::shared_ptr<rosgraph_msgs::msg::Clock_<std::allocator<void> > >)::{lambda(rclcpp::node_interfaces::NodeBaseInterface*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t const&)#1}>::_M_invoke(std::_Any_data const&, rclcpp::node_interfaces::NodeBaseInterface*&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t const&) ()
#16 0x00007ffff7a6547f in std::function<std::shared_ptr<rclcpp::SubscriptionBase> (rclcpp::node_interfaces::NodeBaseInterface*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t const&)>::operator()(rclcpp::node_interfaces::NodeBaseInterface*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rcl_subscription_options_t const&) const () from /home/msaini1/lib/librclcpp.so
#17 0x00007ffff7a64751 in rclcpp::node_interfaces::NodeTopics::create_subscription(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::SubscriptionFactory const&, rcl_subscription_options_t const&, bool) () from /home/msaini1/lib/librclcpp.so
#18 0x00000000004a2aea in std::shared_ptr<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > rclcpp::create_subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, Dc::BagManager::DcRpcPlayer::subscribeClock()::{lambda(std::unique_ptr<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::default_delete<rosgraph_msgs::msg::Clock_<std::allocator<void> > > >)#1}, std::allocator<void>, rosgraph_msgs::msg::Clock_<std::allocator<void> >, rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> >, rclcpp::Node&>(rclcpp::Node&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::QoS const&, Dc::BagManager::DcRpcPlayer::subscribeClock()::{lambda(std::unique_ptr<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::default_delete<rosgraph_msgs::msg::Clock_<std::allocator<void> > > >)#1}&&, rclcpp::SubscriptionOptionsWithAllocator<std::allocator<void> > const&, rclcpp::message_memory_strategy::MessageMemoryStrategy<rosgraph_msgs::msg::Clock_<std::allocator<void> >, rclcpp::SubscriptionOptionsWithAllocator>::SharedPtr) ()
#19 0x00000000004a239a in std::shared_ptr<rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > > rclcpp::Node::create_subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, Dc::BagManager::DcRpcPlayer::subscribeClock()::{lambda(std::unique_ptr<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::default_delete<rosgraph_msgs::msg::Clock_<std::allocator<void> > > >)#1}, std::allocator<void>, rclcpp::Subscription<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::allocator<void> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::QoS const&, Dc::BagManager::DcRpcPlayer::subscribeClock()::{lambda(std::unique_ptr<rosgraph_msgs::msg::Clock_<std::allocator<void> >, std::default_delete<rosgraph_msgs::msg::Clock_<std::allocator<void> > > >)#1}&&, rclcpp::SubscriptionOptionsWithAllocator<std::allocator<void> > const&, rclcpp::message_memory_strategy::MessageMemoryStrategy<rclcpp::subscription_traits::has_message_type<rclcpp::QoS const&, std::enable_if<!std::is_integral<std::remove_cv<std::remove_reference<rclcpp::QoS const&>::type>::type>::value, void>::type, rclcpp::subscription_traits::has_message_type<!std::is_base_of<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::remove_cv<std::remove_reference<rclcpp::QoS const&>::type> >::value, void>::type, rclcpp::subscription_traits::has_message_type<!std::is_same<rmw_qos_profile_t, std::remove_cv<std::remove_reference<rclcpp::QoS const&>::type> >::value, void>::type>::type,

**Comment by clalancette** [comment] 2024-01-03 22:25
Given the age of this, and the fact that it couldn't reproduce later on, I'm going to close this out.  If this is still a problem, please feel free to reopen.

**Closed by clalancette** 2024-01-03 22:25 UTC
Labels: more-information-needed
