### ISSUE TITLE
Payload size exceeding pre-allocated limit.

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/rmw_fastrtps#194] opened 2018-04-12 00:05 UTC
## Bug report

**Required Info:**

- Operating System:
  - Windows 10, MacOS 10.12, Ubuntu Xenial

- Installation type:
  - Build from source on ci.ros2.org

- Version or commit hash:
  - [repos file from vcs export --exact](https://gist.githubusercontent.com/nuclearsandwich/baeaf8123c448cc676228d678395704e/raw/f85414684c826e9188c12c264badde137d4aa06d/rmw_fastrtps_repro.repos)

- DDS implementation:
  - Fast-RTPS

#### Steps to reproduce issue

Reproduced in the following nightly tests on ci.ros2.org

* https://ci.ros2.org/view/nightly/job/nightly_osx_release/820/testReport/(root)/projectroot/test_get_node_names__rmw_fastrtps_cpp/
* https://ci.ros2.org/view/nightly/job/nightly_win_rel/782/testReport/(root)/projectroot/test_subscription_valid_data_cpp__rmw_fastrtps_cpp/
* https://ci.ros2.org/view/nightly/job/nightly_win_rel/782/testReport/(root)/projectroot/test_api_srv_composition_client_first__rmw_fastrtps_cpp/
* https://ci.ros2.org/view/nightly/job/nightly_win_rel/782/testReport/(root)/projectroot/rclpytests/
* https://ci.ros2.org/view/nightly/job/nightly_win_rel/782/testReport/composition.build.composition/test_api_srv_composition_client_first__rmw_fastrtps_cpp_Release/test_api_srv_composition_client_first/

From @mikaelarguedas: this is reproducible on all platforms with the branch from https://github.com/ros2/rcl_interfaces/pull/32

#### Error log excerpt

```
18:25:55 8: [RTPS_HISTORY Error] Change payload size of '6736' bytes is larger than the history payload size of '5000' bytes and cannot be resized. -> Function add_change
18:25:55 8: [RTPS_HISTORY Error] Change payload size of '6736' bytes is larger than the history payload size of '5000' bytes and cannot be resized. -> Function add_change
18:25:55 8: [RTPS_HISTORY Error] Change payload size of '6736' bytes is larger than the history payload size of '5000' bytes and cannot be resized. -> Function add_change
```

#### Additional information

Although I was actually testing something else, a diagnostic job exhibited the error during communication with between fastrtps and opensplice. That job is pending deletion so [the link](https://ci.ros2.org/view/All/job/test_ci_osx-nuclearsandwich/34/) will not be good for long but I've downloaded the full 39MB log if that is of specific interest. It's too big to go into a gist.

From @mikaelarguedas:
> From what I know it comes from this default value https://github.com/eProsima/Fast-RTPS/blob/603580b5186386e47fdc4da2970cd389937840bb/include/fastrtps/rtps/attributes/HistoryAttributes.h#L42
> we are suppose to use a different memory allocation strategy everywhere but for some reason this default is being used for the RTPS endpoints

**Comment by mikaelarguedas** [comment] 2018-07-19 18:15
As we didn't see this a few months and that I'm not able to reproduce, I'm going to close this for now.

I bumped https://github.com/eProsima/Fast-RTPS/issues/213 so that the feature to define the memory strategy for discovery reader/writers can be modified. At that point we should set it to `PREALLOCATED_WITH_REALLOC_MEMORY_MODE` like we do for the other reader/writers

**Closed by mikaelarguedas** 2018-07-19 18:16 UTC
Labels: bug, in progress
