### ISSUE TITLE
[ros2] Configure QoS information from DEFAULT_FASTRTPS_PROFILES.xml and print out

### ISSUE THREAD

**Issue by yangli-flexiv** [ros2/rmw_fastrtps#501] opened 2021-01-12 20:14 UTC
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04 and Ubuntu 20.04
- Installation type:
  - install from binaries
- Version or commit hash:
  - eloquent and foxy of rmw_fastrtps
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
I have created an xml file, DEFAULT_FASTRTPS_PROFILES.xml, to configure the QoS parameters for a publisher node
```
<?xml version="1.0" encoding="UTF-8"?>
<dds xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
  <profiles>

    <publisher profile_name="publisher_profile" is_default_profile="true">
      <topic>
        <historyQos>
          <kind>KEEP_LAST</kind>
          <depth>1</depth>
        </historyQos>
      </topic>

      <qos> <!-- dataWriterQosPoliciesType -->
        <durability>
          <kind>VOLATILE</kind>
        </durability>
        <reliability>
          <kind>BEST_EFFORT</kind>
          <max_blocking_time>
            <sec>0</sec>
            <nanosec>1000000</nanosec>
          </max_blocking_time>
        </reliability>
      </qos>
      <historyMemoryPolicy>DYNAMIC</historyMemoryPolicy>
    </publisher>
  </profiles>
</dds>
```

And I create a node of publisher, which inherits from rclcpp::Node, the publisher is defined by 
```
arm_command_publisher_ =
        this->create_publisher<flexiv_msgs::msg::ArmCommand>("arm_command_topic", 10);
```
Then I want to print out the QoS parameters of this publisher to see whether the settings are the same as what I set in the above xml file. Below is my command:
```
rmw_qos_profile_t qos;
auto rcl_publisher = arm_command_publisher_->get_publisher_handle();
const rmw_publisher_t* rmw_publisher = rcl_publisher_get_rmw_handle(rcl_publisher);
rmw_publisher_get_actual_qos(rmw_publisher, &qos);

std::cout << "qos.history = " << qos.history << std::endl;
std::cout << "qos.depth = " << qos.depth << std::endl;
std::cout << "qos.reliability = " << qos.reliability << std::endl;
std::cout << "qos.durability = " << qos.durability << std::endl;
```
The required headers are included at the beginning. 

After I build the code, and source both setup.bash files of standard ros2 and my repo, I typed in the command in my terminal:
```
FASTRTPS_DEFAULT_PROFILES_FILE=DEFAULT_FASTRTPS_PROFILES.xml RMW_FASTRTPS_USE_QOS_FROM_XML=1 RMW_IMPLEMENTATION=rmw_fastrtps_cpp ros2 run <package_name> <executable_name>
```
The app can be executed, and I got the following prints:
```
qos.history = 1
qos.depth = 10
qos.reliability = 1
qos.durability = 2
```
Obviously, the depth (10) is different from what I set in the xml (1). 

I tried to modify the label keyword (such as giving it garbage name <profilessfsfd>), running the binary will report the error, saying the file can't be parsed because of unknown keywords. Also, when I tried to change the name of the xml but keep the command in the terminal the same, when execute, it also report no such file can be found and parsed. 
```
2021-01-12 12:07:28.552 [XMLPARSER Error] Error opening 'DEFAULT_FASTRTPS_=PROFILES.xml' -> Function loadXML
2021-01-12 12:07:28.552 [XMLPARSER Error] Error parsing 'DEFAULT_FASTRTPS_=PROFILES.xml' -> Function loadXMLFile
```
So I think the original xml file is correctly parsed. 

I tested my code in both eloquent and foxy of ros2 on Ubuntu 18.04 and Ubuntu 20.04, but the same error happens. 

I don't know why the error happens. One thing I guess is I do the setting in the eprosima environment, as DEFAULT_FASTRTPS_PROFILES.xml is proposed by eprosima to configure QoS for publisher and subscriber, etc.; while I use the QoS API's in ros2 environment to print out. I am not sure whether information in DEFAULT_FASTRTPS_PROFILES.xml is correctly set to my publisher, though I believe it has been parsed.

Can anyway help me on this? Usually, what is the correct way to print the QoS information after one programmed DEFAULT_FASTRTPS_PROFILES.xml, to verify the values are correctly set to QoS parameters?

Thanks!

#### Additional information

----

**Comment by clalancette** [comment] 2021-01-12 20:38
As far as I can tell, this is a duplicate of #500 , so I'm going to close this one.

**Closed by clalancette** 2021-01-12 20:38 UTC
