### ISSUE TITLE
Subscriber which is created with dedicated callback group at runtime not working

### ISSUE THREAD

**Issue by gezp** [ros2/rmw_fastrtps#613] opened 2022-06-16 09:06 UTC
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu22.04
- Installation type:
  - Rolling binaries 
- Version or commit hash:
  - Rolling
- DDS implementation:
  - default
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

i create a minimal package to reproduce this issue, see more detail here :https://github.com/gezp/ros2_test_subscriber
```
ros2 launch ros2_test_subscriber test_subscriber.launch.py use_dedicated_thread:=True
```

#### Expected behavior
* subscriber working when activate (in other word, create subscriber), 

#### Actual behavior
* subscriber keeps not working

#### Additional information

see detailed output here: https://github.com/gezp/ros2_test_subscriber. by the way, it works well under ubuntu20.04 ROS Galactic. 

i'm working for nav2, here are some related PRs([navigation2/#2489](https://github.com/ros-planning/navigation2/pull/2489),  [navigation2/#3018](https://github.com/ros-planning/navigation2/pull/3018)).  [navigation2/#2489](https://github.com/ros-planning/navigation2/pull/2489) worked well when my env was under ubuntu20.04 ROS Rolling, and when i updated my env to ubuntu22.04 ROS Rolling, [navigation2/#2489](https://github.com/ros-planning/navigation2/pull/2489) broke the expected behavior.
CC @SteveMacenski

**Comment by ros-discourse** [comment] 2022-06-21 19:09
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/fastdds-without-discovery-server/26117/2

**Comment by ros-discourse** [comment] 2022-06-21 20:15
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/nav2-issues-with-humble-binaries-due-to-rmw-regression/26128/1

**Comment by EduPonz** [comment] 2022-06-27 07:09
We are currently working on a solution for this (#619) which fixes this issue for us locally. It is still missing some work which will be ready this week.

**Comment by clalancette** [comment] 2022-06-27 12:10
> We are currently working on a solution for this (#619) which fixes this issue for us locally. It is still missing some work which will be ready this week.

Fantastic, thanks for the update.

**Comment by afrixs** [comment] 2022-07-21 13:46
Just to note, we have recently discussed a similar issue in navigation2 with a timer being registered to an executor from an external thread. [Conclusion](https://github.com/ros2/rmw_fastrtps/issues/606#issuecomment-1125824269) was that if a node is assigned to multiple executors running asynchronously, it is unable to notify all of them about creating/destroying subscriptions etc..

There is a note about violating RMW API by this behavior in the linked comment, stating that it is more of rclcpp problem (although making FastDDS support this would be really nice of course). There has already been [an issue about it](https://github.com/ros2/rclcpp/issues/1611) for a long time in rclcpp and even a [pull request](https://github.com/ros2/rclcpp/pull/1640) fixing the problem by using a separate guard condition per callback group instead of per node, but it hasn't been merged for some reason until now, which is a shame, since this has a strong impact on elegance of the system, causing so many head-aches.

Maybe @gezp or someone who uses rclcpp built from source, could you try to test [the example](https://github.com/gezp/ros2_test_subscriber) with [this patch](https://github.com/ros2/rclcpp/pull/1640) applied? I'm quite convinced it will work.

Another way to make the example work is to use a separate node for each asynchronous executor, i.e. applying [this diff](https://github.com/ros2/rmw_fastrtps/files/9159822/ros2_test_subscriber_diff.txt). However it's quite inelegant, introducing many unneeded nodes in the system.

**Comment by MiguelCompany** [comment] 2022-07-21 14:10
@afrixs 

> although making FastDDS support this would be really nice of course

That is what #619 is about. Would be great if someone could also give it a try.

**Comment by SteveMacenski** [comment] 2022-07-21 16:37
@afrixs I'll try to escalate https://github.com/ros2/rclcpp/pull/1640 - I agree, it probably just got buried

**Comment by fujitatomoya** [comment] 2022-08-25 05:32
@SteveMacenski @gezp I confirmed that this problem has been addressed by https://github.com/ros2/rmw_fastrtps/pull/619. please feel free to reopen if you still have this issue in rolling.

**Closed** 2022-08-25 05:32 UTC
